spring.application.name=bff-agendador-de-tarefas

usuario.url=${USUARIO_URL:localhost:8080/usuario}
agendador-tarefas.url=${AGENDADOR_TAREFAS_URL:localhost:8081/tarefas}
notificacao.url=${NOTIFICACAO_URL:localhost:8082/email}

server.port=8083

# Headers para ler os IPs e Protocolos do Nginx
server.forward-headers-strategy=framework

# Forca o Swagger a usar a URL do Nginx para gerar os botoes de "Execute", evitando erros de CORS e de HTTPS
springdoc.swagger-ui.path=/swagger-ui.html

# Spring Boot agora so le requisicoes que comecam com /api
server.servlet.context-path=/api


usuario.email=${USER_USERNAME}
usuario.senha=${USER_PASSWORD}

cron.horario=0 0/5 * * * ?